server.address=0.0.0.0
server.port=${PORT:80}
spring.application.name=gateway
services.catalog-url=${CATALOG_URL:http://localhost:8081}
services.inventory-url=${INVENTORY_URL:http://localhost:8082}
services.reviews-url=${REVIEWS_URL:http://localhost:8083}
